"""add_workflow_stage_to_clients

Revision ID: e72d4612ff67
Revises: f35ad26ae118
Create Date: 2026-05-15 11:18:47.431404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72d4612ff67'
down_revision = 'f35ad26ae118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_stage', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('exclusion_rules', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('meeting_notes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'meetings', ['meeting_id'], ['id'])

    with op.batch_alter_table('meeting_reviews', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'meetings', ['meeting_id'], ['id'])

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('meeting_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('meeting_notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('exclusion_rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('workflow_stage')

    # ### end Alembic commands ###
